# System testing preCICE with fenics-adapter

# Building on top of the latest preCICE-build
ARG branch=develop
ARG from=precice/precice-ubuntu1804.home-${branch}
FROM $from

USER root
ENV USER=root
ENV DEBIAN_FRONTEND=noninteractive

# Installing necessary dependencies
RUN apt-get -qq update && apt-get -qq install \
    apt-utils && \
    apt-get -qq install \
    software-properties-common \
    python3-dev \
    python3-pip && \
    rm -rf /var/lib/apt/lists/*


# Install FEniCS
RUN add-apt-repository -y ppa:fenics-packages/fenics && \
    apt-get -qq update && \
    apt-get -qq install --no-install-recommends fenics && \
    rm -rf /var/lib/apt/lists/*

USER precice

# Upgrade pip to newest version (pip version from 18.04 apt-get is outdated)
RUN python3 -m pip install --user --upgrade pip
# Use pip to install cython (apt-get version of cython is too old)
RUN python3 -m pip install --user cython # TODO: can we put this dependency into requirements.txt of python?

# Rebuild image if force_rebuild after that command
ARG CACHEBUST

ARG bindings_branch=develop
ARG adapter_branch=develop

# Builds the precice python bindings for python3
RUN python3 -m pip install --user https://github.com/precice/python-bindings/archive/$bindings_branch.zip

# Building fenics-adapter
RUN python3 -m pip install --user numpy==1.14.5 https://github.com/precice/fenics-adapter/archive/$adapter_branch.zip


# ----- TODO: Remove this block after fenics issue is fixed -----
# At the moment, attempting to use fenics causes an ImportError
# Uninstalling fenics-ufl will resolve this problem.
RUN pip3 uninstall -y fenics-ufl
# ---------------------------------------------------------------

WORKDIR /home/precice
RUN mkdir -p Logs Data/Input Data/Output Data/Exchange
WORKDIR /home/precice/fenics-adapter
